name: Release

on:
  pull_request: 
    branches:
      - main
    types: 
      - closed
jobs:
  release:
    if: github.event.pull_request.merged && ${{ startsWith(github.event.pull_request.head.ref, 'releases/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: |
          echo "Releasing"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@shaunxu'
      - run: |
           node app.js