name: Release

on:
  pull_request: 
    branches:
      - main
    types: [closed]
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR Closed"
      - run: |
          echo "PR Merged"
        if: github.event.pull_request.merged
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT